var PORT_NUMBER, app, home, b;
var _ = require('underscore');
var jade = require("jade");
var lessMiddleware = require('less-middleware');
var express = require("express");
var browserify = require('browserify-middleware');
var bodyParser = require("body-parser");

home = __dirname;

app = express();
app.use(bodyParser.urlencoded({ extended: false }));

app.set("views", home + "/views");
app.set("view engine", "jade");

app.use(lessMiddleware(home + '/style', {debug: true}));
app.use(express.static(home + "/style"));

app.get('/client/main.js', browserify(home + '/client/main.js'));

app.use("/img", express.static(home + "/img"));
app.use("/vendor", express.static(home + "/vendor"));


app.get("/", function(req, res) {
  return res.render("home");
});

app.post("/results", function(req, res) {
  console.log(req.body);
  return res.render("results", req.body);
});

// app.post("/results2", function(req, res) {
//   console.log(req.body);
//   return res.render("results", {someresult: "awdianwoidnand"});
// });

// app.get("/games/:id", function(req, res) {
//   if (req.headers["x-pjax"] != null) {
//     return res.render("game-partial", {
//       gameId: req.params.id
//     });
//   } else {
//     return res.render("game", {
//       gameId: req.params.id
//     });
//   }
// });

// app.get("/scoreboard", function(req, res) {
//   if (req.headers["x-pjax"] == null) {
//     res.status(417);
//     res.end();
//   }
//   return res.render("scoreboard");
// });

// PORT_NUMBER = 2020;

PORT_NUMBER = 6060;

app.listen(process.env.PORT || PORT_NUMBER);

console.log("Express app started on port %d", PORT_NUMBER);

// ---
// generated by coffee-script 1.9.0
